spring.application.name=backend

spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@confluo-cluster.nh8oqx3.mongodb.net/confluo?appName=confluo-cluster